'use server';
/**
 * @fileOverview A Genkit flow for generating new text content based on a user's natural language prompt.
 *
 * - generateNewContentFromPrompt - A function that handles the content generation process.
 * - GenerateNewContentFromPromptInput - The input type for the generateNewContentFromPrompt function.
 * - GenerateNewContentFromPromptOutput - The return type for the generateNewContentFromPrompt function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateNewContentFromPromptInputSchema = z.object({
  prompt: z.string().describe('The natural language prompt provided by the user.'),
});
export type GenerateNewContentFromPromptInput = z.infer<typeof GenerateNewContentFromPromptInputSchema>;

const GenerateNewContentFromPromptOutputSchema = z.object({
  generatedContent: z.string().describe('The new text content generated by the AI.'),
});
export type GenerateNewContentFromPromptOutput = z.infer<typeof GenerateNewContentFromPromptOutputSchema>;

export async function generateNewContentFromPrompt(input: GenerateNewContentFromPromptInput): Promise<GenerateNewContentFromPromptOutput> {
  return generateNewContentFlow(input);
}

const contentGenerationPrompt = ai.definePrompt({
  name: 'contentGenerationPrompt',
  input: { schema: GenerateNewContentFromPromptInputSchema },
  output: { schema: GenerateNewContentFromPromptOutputSchema },
  prompt: `Generate new text content based on the following prompt:

{{{prompt}}}`,
});

const generateNewContentFlow = ai.defineFlow(
  {
    name: 'generateNewContentFlow',
    inputSchema: GenerateNewContentFromPromptInputSchema,
    outputSchema: GenerateNewContentFromPromptOutputSchema,
  },
  async (input) => {
    const { output } = await contentGenerationPrompt(input);
    if (!output) {
      throw new Error('Failed to generate content.');
    }
    return output;
  }
);
